#!/bin/bash

# This is a personal environment setting script of Xingyu Su
# You can find me at http://suxy.info
#  ____       __  ____   __
# / ___| _   _\ \/ /\ \ / /
# \___ \| | | |\  /  \ V / 
#  ___) | |_| |/  \   | |  
# |____/ \__,_/_/\_\  |_|  
#
# Copyright 2019 Xingyu Su

# = = = = = = = = = = = = = = = = 
# for env
export PATH="/usr/local/sbin:/usr/local/bin:$PATH"

# = = = = = = = = = = = = = = = = 
# for zsh
export ZSH="$HOME/.oh-my-zsh"
plugins=(
    zsh-autosuggestions zsh-syntax-highlighting git autojump extract
)
ZSH_THEME="fishy"
COMPLETION_WAITING_DOTS="true"

source $ZSH/oh-my-zsh.sh

# = = = = = = = = = = = = = = = = 
# for python
alias python='/usr/bin/env python3'
alias python2='/usr/bin/env python'
alias pip='/usr/bin/env pip3'
alias pip2='/usr/bin/env pip'
alias note="jupyter notebook"

# = = = = = = = = = = = = = = = = 
# for git
alias gs='git status'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push'

# = = = = = = = = = = = = = = = = 
# for vim

# = = = = = = = = = = = = = = = = 
# for servers
alias gpu='ssh suxy15@166.111.17.73 -p 2222'
alias arch='ssh suxy@101.6.61.53'
alias arsh='ssh share@101.6.61.53'
alias win='ssh Xingyu\ Su@101.6.61.51'

# = = = = = = = = = = = = = = = = 
# for convenience
alias inet='ifconfig | grep inet\ '
alias htop="htop --sort-key PERCENT_CPU"

# = = = = = = = = = = = = = = = = 
# zsh functions
# find $2 in $1 with name matching
ft(){
    find . -name "$2" -exec grep -il "$1" {} \;
}

# mkdir and cd
mcd(){
    mkdir -p "$1" && cd "$1";
}

# extract files
ext () {
    if [ -f $1 ] ; then
      case $1 in
        *.tar.bz2)   tar xjf $1     ;;
        *.tar.gz)    tar xzf $1     ;;
        *.bz2)       bunzip2 $1     ;;
        *.rar)       unrar e $1     ;;
        *.gz)        gunzip $1      ;;
        *.tar)       tar xf $1      ;;
        *.tbz2)      tar xjf $1     ;;
        *.tgz)       tar xzf $1     ;;
        *.zip)       unzip $1       ;;
        *.Z)         uncompress $1  ;;
        *.7z)        7z x $1        ;;
        *)     echo "'$1' cannot be extracted via extract()" ;;
         esac
     else
         echo "'$1' is not a valid file"
     fi
}

# encode some files
encode(){
  echo -n "Encrypt password:"
  read -s passwd
  echo ""
  for i in $*
  do
    echo $i
    openssl enc -e -aes-128-cbc -in $i -out en${i:2} -pass pass:$passwd
  done
}

# decode some files
decode(){
  echo -n "Password required:"
  read -s passwd
  echo ""
  for i in $*
  do
    echo $i
    openssl enc -d -aes-128-cbc -in $i -out de${i:2} -pass pass:$passwd
  done
}

